=== devmehta-simform/json-and-xml/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="productsList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="product" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string">
                            </xs:element>
                            <xs:element name="price" type="xs:positiveInteger" />
                            <xs:element name="description" type="xs:string" minOccurs="0"
                                maxOccurs="1" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:positiveInteger" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="id_unique">
            <xs:selector xpath="product"></xs:selector>
            <xs:field xpath="@id"></xs:field>
        </xs:unique>
        <xs:unique name="name_unique">
            <xs:selector xpath="product/name" />
            <xs:field xpath="." />
        </xs:unique>
    </xs:element>
</xs:schema>

=== devmehta-simform/json-and-xml/data.xml
<productsList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="data.xsd">
    <product id="1">
        <name>product1</name>
        <price>12</price>
        <description>this is product1</description>
    </product>
    <product id="2">
        <name>product2</name>
        <price>14</price>
        <description>this is product2</description>
    </product>
    <product id="3">
        <name>product3</name>
        <price>16</price>
    </product>
    <product id="4">
        <name>product4</name>
        <price>18</price>
    </product>
    <product id="5">
        <name>product5</name>
        <price>20</price>
        <description>this is product5</description>
    </product>
</productsList>
